name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: make install

        #      - name: Run lint
        #        run: make lint

        #      - name: Run typecheck
        #        run: make typecheck

        #      - name: Run format check
        #        run: make format

      - name: Run tests
        run: make test

      # could use only "make check" for the above 4 steps
